// Generated by LiveScript 1.3.1
(function(){
  var prevent_bust;
  console.log('yet');
  prevent_bust = 0;
  window.onbeforeunload = function(){
    return prevent_bust++;
  };
  setInterval(function(){
    if (prevent_bust > 0) {
      prevent_bust -= 2;
      return window.top.location = 'http://null.localhost/';
    }
  }, 1);
}).call(this);
