// Generated by LiveScript 1.3.1
(function(){
  var app;
  app = angular.module('BookmarksManagerApp', ['ui.router']);
  app.config(function($compileProvider, $stateProvider, $urlRouterProvider, $locationProvider){
    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|chrome-extension):/);
    $urlRouterProvider.otherwise('/bookmarks');
    return $stateProvider.state('bookmarks', {
      abstract: true,
      url: '/bookmarks',
      templateUrl: '/app/templates/bookmarks/index.html'
    }).state('bookmarks.list', {
      url: '',
      templateUrl: '/app/templates/bookmarks/list.html'
    });
  });
  app.controller('MainCtrl', [
    '$sce', '$scope', function($sce, $scope){
      $scope.trustSrc = function(src){
        return $sce.trustAsResourceUrl(src);
      };
      return chrome.bookmarks.getRecent(100, function(data){
        return $scope.bookmarks = data;
      });
    }
  ]);
}).call(this);
